[workspace]
authors = ["obi <ole.bialas@posteo.de>"]
channels = ["conda-forge"]
name = "Introduction-to-Scientific-Data-Management-with-DataLad"
platforms = ["linux-64", "win-64", "osx-64"]
version = "0.1.0"

[tasks]
install-kernel = "python -m ipykernel install --name datalad-wshop"

[dependencies]
python = "3.12.*"
ipykernel = "*"
rclone = ">=1.72.0,<2"

[pypi-dependencies]
datalad = ">=1.2.3, <2"
datalad-next = ">=1.5.0, <2"
git-annex = ">=10.20250721, <11"
ipykernel = "*"
datalad-osf = ">=0.3.0, <0.4"
pandas = ">=2.3.3, <3"
matplotlib = ">=3.10.7, <4"
seaborn = ">=0.13.2, <0.14"
